name: monkey

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  go-tests:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -count=1 -v ./...
