name: monkey

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  go-tests:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -count=1 -v ./...

  cpp-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: ['clang++-14', 'g++']

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Build with CMake
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: 'CMakeListsTxtAdvanced'
        cmakeListsTxtPath: '${{ github.workspace }}/transpiler/runtime/CMakeLists.txt'
        cmakeAppendedArgs: '-DBUILD_TESTS=ON'
        buildDirectory: '${{ github.workspace }}/transpiler/runtime/build'
      env:
        CXX: ${{ matrix.compiler }}
    - name: Execute tests
      run: '${{ github.workspace }}/transpiler/runtime/build/runtime_test'
